### ISSUE TITLE
When the RemoteServiceAdmin doesn't become available even if a Hazelcast join eventually succees, the FelixStartLevel thread gets blocked.

### ISSUE THREAD

**Issue by rmoquin** [ECF/HazelcastProvider#2] opened 2019-10-20 01:59 UTC
This is using a bnd 4.3.0 packaged Felix 6 app.

This seems to happen when a new node joins the discovery Hazelcast cluster for discovery and even though the connection succeeds, the RemoteServiceAdmin service takes too long to become available, for example:

Oct 19, 2019 9:37:34 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.29.48.1]:5701 [hazelcastdiscovery] [3.12.3] Initialized new cluster connection between /198.**.**.*:51858 and hostname/10.***.**.***:5701
(TRACE)[10/19/19;21:37:42:829]CAUGHT RemoteServiceAdmin did not become active in 20000ms (org.eclipse.ecf.osgi.services.remoteserviceadmin.TopologyManagerImpl#exportRegisteredServices:Could not retrieve existing service references for exportRegisteredSvcsFilter=(service.exported.interfaces=*))
java.util.concurrent.TimeoutException: RemoteServiceAdmin did not become active in 20000ms
        at org.eclipse.ecf.osgi.services.remoteserviceadmin.TopologyManagerImpl$1.run(TopologyManagerImpl.java:170)
        at java.base/java.lang.Thread.run(Thread.java:834)

This results in startup hanging for it looks like 7+ minutes because the FelixStartLevel thread gets blocked, for example:

"FelixStartLevel" - Thread t@24
   java.lang.Thread.State: TIMED_WAITING
	at java.base@11.0.4/java.lang.Thread.sleep(Native Method)
	at com.hazelcast.cluster.impl.TcpIpJoiner.tryJoinAddresses(TcpIpJoiner.java:265)
	at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:144)
	at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:98)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:137)
	at com.hazelcast.instance.Node.join(Node.java:809)
	at com.hazelcast.instance.Node.start(Node.java:444)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.hazelcast.osgi.impl.HazelcastOSGiServiceImpl.createHazelcastInstance(HazelcastOSGiServiceImpl.java:112)
	at com.hazelcast.osgi.impl.HazelcastOSGiServiceImpl.newHazelcastInstance(HazelcastOSGiServiceImpl.java:240)
	- locked <46ff7d87> (a java.lang.Object)
	at org.eclipse.ecf.discovery.provider.hazelcast.container.HazelcastDiscoveryContainer.connect(HazelcastDiscoveryContainer.java:203)
	- locked <63000a4d> (a java.util.Collections$SynchronizedMap)
	at org.eclipse.ecf.discovery.provider.hazelcast.Activator.getHazelcastContainer(Activator.java:257)
	- locked <6c2c4bfd> (a org.eclipse.ecf.discovery.provider.hazelcast.Activator)
	at org.eclipse.ecf.discovery.provider.hazelcast.Activator$1.getService(Activator.java:230)
	at org.eclipse.ecf.discovery.provider.hazelcast.Activator$1.getService(Activator.java:1)
	at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:348)
	at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:248)
	at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:350)
	at org.apache.felix.framework.Felix.getService(Felix.java:3954)
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:450)
	at org.eclipse.ecf.osgi.services.remoteserviceadmin.EndpointDescriptionLocator$LocatorTrackerCustomizer.addingService(EndpointDescriptionLocator.java:701)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
	at org.eclipse.ecf.discovery.provider.hazelcast.Activator.start(Activator.java:225)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.eclipse.ecf.internal.osgi.services.remoteserviceadmin.Activator.initializeProviders(Activator.java:126)
	at org.eclipse.ecf.internal.osgi.services.remoteserviceadmin.Activator.start(Activator.java:334)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base@11.0.4/java.lang.Thread.run(Thread.java:834)

Eventually this happens:

org.eclipse.ecf.core.ContainerConnectException: Could not create hazelcast instance with hazelcastConfig=Config...
        at org.eclipse.ecf.discovery.provider.hazelcast.container.HazelcastDiscoveryContainer.connect(HazelcastDiscoveryContainer.java:209)
        at org.eclipse.ecf.discovery.provider.hazelcast.Activator.getHazelcastContainer(Activator.java:257)
        at org.eclipse.ecf.discovery.provider.hazelcast.Activator$1.getService(Activator.java:230)
        at org.eclipse.ecf.discovery.provider.hazelcast.Activator$1.getService(Activator.java:1)
        at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:348)
        at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:248)
        at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:350)
        at org.apache.felix.framework.Felix.getService(Felix.java:3954)
        at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:450)
        at org.eclipse.ecf.osgi.services.remoteserviceadmin.EndpointDescriptionLocator$LocatorTrackerCustomizer.addingService(EndpointDescriptionLocator.java:701)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
        at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
        at org.eclipse.ecf.discovery.provider.hazelcast.Activator.start(Activator.java:225)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)

Then the startup continues.. maybe an additional thread can be use to prevent this sort of thing from happening when there are connection issues?

**Comment by scottslewis** [comment] 2019-10-20 02:45
It appears to me that both of these exceptions/stack traces are caused by a failed connection to the Hazelcast discovery group.   

For RS discovery it's critical that the join/connect succeed and not block for a long time...as it appears to be doing above. 

When RSA starts up, it starts a thread to check to see if any remote services that have been registered *before* RSA starts (since in general we can't control start order), and if it finds some/any then it exports them.   But before it can export them, discovery has to be started to be able to publish the endpoint description.   If the discovery blocks trying to join (for a very long time) then the RSA thread fails with timeout waiting for things to get initialized and produces this output:

TRACE)[10/19/19;21:37:42:829]CAUGHT RemoteServiceAdmin did not become active in 20000ms (org.eclipse.ecf.osgi.services.remoteserviceadmin.TopologyManagerImpl#exportRegisteredServices:Could not retrieve existing service references for exportRegisteredSvcsFilter=(service.exported.interfaces=))
java.util.concurrent.TimeoutException: RemoteServiceAdmin did not become active in 20000ms
at org.eclipse.ecf.osgi.services.remoteserviceadmin.TopologyManagerImpl$1.run(TopologyManagerImpl.java:170)
at java.base/java.lang.Thread.run(Thread.java:834)

FYI:   This RSA startup timeout can be changed via a system property:

-Dorg.eclipse.ecf.osgi.services.remoteserviceadmin.startupWaitTime=20000 // default

But I think it would be better to simply assure that the discovery join/connect/create Hazelcast instance happens much faster and that it happens reliably...or at least doesn't block.

What would cause HC to take so long to connect...or take so long to fail on connect?   I would guess that there must be some HC configuration that would allow a quicker connect time?

**Comment by scottslewis** [comment] 2020-06-09 21:04
I do not think that the delay described is caused by ECF, but rather something about the Hazelcast discovery and/or distribution.   If more info is found pointing to ECF specifically, please reopen. 
  Closing.

**Closed as completed by scottslewis** 2020-06-09 21:04 UTC
